#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH

if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then
  if [ ! -f $OPENSHIFT_DATA_DIR/bin/python ]; then
    # install python 2.7.6
    cd $OPENSHIFT_TMP_DIR
    wget http://python.org/ftp/python/2.7.6/Python-2.7.6.tgz
    tar zxf Python-2.7.6.tgz
    cd Python-2.7.6
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make install
  fi

  # install setuptools and pip
  cd $OPENSHIFT_TMP_DIR
  wget --no-check-certificate https://pypi.python.org/packages/source/s/setuptools/setuptools-2.0.1.tar.gz
  tar zxf setuptools-2.0.1.tar.gz
  cd setuptools-2.0.1
  python setup.py install
  cd $OPENSHIFT_TMP_DIR
  wget --no-check-certificate https://pypi.python.org/packages/source/p/pip/pip-1.4.1.tar.gz
  tar zxf pip-1.4.1.tar.gz
  cd pip-1.4.1
  python setup.py install

  # cleanup
  rm -rf $OPENSHIFT_TMP_DIR/*
fi

