#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH
cd $OPENSHIFT_REPO_DIR
python -m supervisor.supervisord -c supervisord-wsgi.conf

